CREATE TABLE EMPRESAS (
	CIF	TEXT PRIMARY KEY,
	RAZON_SOCIAL	TEXT NOT NULL UNIQUE,	
	DOMICILIO	TEXT NOT NULL,
	REPRESENTANTE_LEGAL	TEXT NOT NULL,
	CORREO_RL	TEXT NOT NULL,
	CONVENIO	TEXT NOT NULL,
	NUM_EMPLEADOS	INTEGER,
	TELEFONO	TEXT,	
	WEB	TEXT,
	CONSTRAINT CHCK_CONVENIO CHECK(CONVENIO IN ('SI', 'NO'))
);
